INSERT INTO TRANSPORT_MANAGEMENT.DESTINATION_CHARGES
VALUES('Zone1','Zone2',40.00);
INSERT INTO TRANSPORT_MANAGEMENT.DESTINATION_CHARGES
VALUES('Zone2','Zone1',40.00);
INSERT INTO TRANSPORT_MANAGEMENT.DESTINATION_CHARGES
VALUES('Zone3','Zone1',65.00);

INSERT INTO TRANSPORT_MANAGEMENT.PASSENGER
(USER_ID,FULLNAME,EMAIL,PHONE,AVAILABLE_BALANCE,MEMBERSHIP_START_DATE,MEMBERSHIP_END_DATE, CARD_STATUS)
VALUES(1,'JhonDoe','jhon.doe@gmail.com','0112345567',0,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),1);
INSERT INTO TRANSPORT_MANAGEMENT.PASSENGER
(USER_ID,FULLNAME,EMAIL,PHONE,AVAILABLE_BALANCE,MEMBERSHIP_START_DATE,MEMBERSHIP_END_DATE, CARD_STATUS)
VALUES(2,'JamesW','jamesw@gmail.com','0112345568',120.00,CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(),1);

INSERT INTO TRANSPORT_MANAGEMENT.JOURNEY
(START_ZONE,END_ZONE,START_TIME,END_TIME,AMOUNT,JOURNEY_STATE,USER_ID)
VALUES('Zone1','Zone2',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),40.00,2,1);
INSERT INTO TRANSPORT_MANAGEMENT.JOURNEY
(START_ZONE,END_ZONE,START_TIME,END_TIME,AMOUNT,JOURNEY_STATE,USER_ID)
VALUES('Zone1','Zone3',CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP(),65.00,2,2);