CREATE SCHEMA TRANSPORT_MANAGEMENT;

-- creating the table TRANSPORT_MANAGEMENT.DESTINATION_CHARGES
CREATE TABLE TRANSPORT_MANAGEMENT.DESTINATION_CHARGES(
  START_ZONE VARCHAR(50) NOT NULL,
  END_ZONE VARCHAR(50) NOT NULL,
  AMOUNT DECIMAL(10,2) NOT NULL
);
ALTER TABLE TRANSPORT_MANAGEMENT.DESTINATION_CHARGES ADD PRIMARY KEY (START_ZONE,END_ZONE);

-- creating the table TRANSPORT_MANAGEMENT.PASSENGER
CREATE TABLE TRANSPORT_MANAGEMENT.PASSENGER(
  PASSENGER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_ID BIGINT NOT NULL,
  FULLNAME VARCHAR(50) NOT NULL,
  EMAIL VARCHAR(50) NOT NULL,
  PHONE VARCHAR(50) NOT NULL,
  AVAILABLE_BALANCE DECIMAL(10,2) NOT NULL,
  MEMBERSHIP_START_DATE DATE NOT NULL,
  MEMBERSHIP_END_DATE DATE NOT NULL,
  CARD_STATUS TINYINT(1) NOT NULL
);

-- creating the table TRANSPORT_MANAGEMENT.JOURNEY
CREATE TABLE TRANSPORT_MANAGEMENT.JOURNEY (
  JOURNEY_ID  BIGINT AUTO_INCREMENT  PRIMARY KEY,
  START_ZONE VARCHAR(50) NOT NULL,
  END_ZONE VARCHAR(50) NOT NULL,
  START_TIME DATE NOT NULL,
  END_TIME DATE DEFAULT NULL,
  AMOUNT DECIMAL(10,2) DEFAULT NULL,
  JOURNEY_STATE TINYINT(1) NOT NULL,
  USER_ID BIGINT NOT NULL,
  FOREIGN KEY(START_ZONE) REFERENCES TRANSPORT_MANAGEMENT.DESTINATION_CHARGES(START_ZONE)
);