CREATE TABLE USER_DETAILS_SERVICE.SYSTEM_USER (
  USER_ID bigint NOT NULL,
  USER_NAME varchar(50) NOT NULL,
  PASSWORD varchar(50) NOT NULL,
  DESCRIPTION varchar(100) NOT NULL,
  PRIMARY KEY (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ;

CREATE TABLE USER_DETAILS_SERVICE.SYSTEM_ROLES (
  ROLE_ID bigint NOT NULL,
  ROLE_NAME varchar(50) NOT NULL,
  AUTH_BIN_VALUE bigint DEFAULT 0,
  DESCRIPTION varchar(100) NOT NULL,
  PRIMARY KEY (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE USER_DETAILS_SERVICE.SYSTEM_USER_ROLES (
  ROLE_ID bigint NOT NULL,
  USER_ID bigint NOT NULL,
  DESCRIPTION varchar(100) NOT NULL,
  PRIMARY KEY (`ROLE_ID`,`USER_ID`),
  FOREIGN KEY(`ROLE_ID`) REFERENCES USER_DETAILS_SERVICE.SYSTEM_ROLES(`ROLE_ID`),
  FOREIGN KEY(`USER_ID`) REFERENCES USER_DETAILS_SERVICE.SYSTEM_USER(`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci