CREATE TABLE TRANSPORT_MANAGEMENT.JOURNEY(
  JOURNEY_ID bigint auto_increment NOT NULL,
  START_ZONE varchar(50) NOT NULL,
  END_ZONE varchar(50) NOT NULL,
  START_TIME datetime NOT NULL,
  END_TIME datetime DEFAULT NULL,
  AMOUNT decimal(10,2) DEFAULT NULL,
  JOURNEY_STATE tinyint(1) NOT NULL,
  USER_ID bigint NOT NULL,
  PRIMARY KEY (`JOURNEY_ID`),
  FOREIGN KEY(`START_ZONE`) REFERENCES TRANSPORT_MANAGEMENT.DESTINATION_CHAGRES(`START_ZONE`)
  -- FOREIGN KEY(`END_ZONE`) REFERENCES TRANSPORT_MANAGEMENT.DESTINATION_CHAGRES(`END_ZONE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE TRANSPORT_MANAGEMENT.DESTINATION_CHARGES(
  START_ZONE varchar(50) NOT NULL,
  END_ZONE varchar(50) NOT NULL,
  AMOUNT decimal(10,2) NOT NULL,
  PRIMARY KEY (`START_ZONE`,`END_ZONE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE TRANSPORT_MANAGEMENT.MEMBERSHIP(
  MEMBERSHIP_ID bigint NOT NULL,
  USER_ID bigint NOT NULL,
  FULLNAME varchar(50) NOT NULL,
  EMAIL varchar(50) NOT NULL,
  PHONE varchar(50) NOT NULL,
  AVAILABLE_BALANCE decimal(10,2) NOT NULL,
  MEMBERSHIP_START_DATE date NOT NULL,
  MEMBERSHIP_END_DATE date NOT NULL,
  CARD_STATUS tinyint(1) NOT NULL,
  PRIMARY KEY (`MEMBERSHIP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;