CREATE TABLE TRANSPORT_MANAGEMENT.DESTINATION_CHARGES(
  START_ZONE varchar(50) NOT NULL,
  END_ZONE varchar(50) NOT NULL,
  AMOUNT decimal(10,2) NOT NULL,
  PRIMARY KEY (`START_ZONE`,`END_ZONE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE TRANSPORT_MANAGEMENT.JOURNEY(
  JOURNEY_ID bigint auto_increment NOT NULL,
  START_ZONE varchar(50) NOT NULL,
  END_ZONE varchar(50) NOT NULL,
  START_TIME datetime NOT NULL,
  END_TIME datetime DEFAULT NULL,
  AMOUNT decimal(10,2) DEFAULT NULL,
  JOURNEY_STATE tinyint(1) NOT NULL,
  USER_ID bigint NOT NULL,
  PRIMARY KEY (`JOURNEY_ID`),
  FOREIGN KEY(`START_ZONE`) REFERENCES TRANSPORT_MANAGEMENT.DESTINATION_CHARGES(`START_ZONE`)
  -- FOREIGN KEY(`END_ZONE`) REFERENCES TRANSPORT_MANAGEMENT.DESTINATION_CHARGES(`END_ZONE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


CREATE TABLE TRANSPORT_MANAGEMENT.PASSENGER(
  PASSENGER_ID bigint NOT NULL,
  USER_ID bigint NOT NULL,
  FULLNAME varchar(50) NOT NULL,
  EMAIL varchar(50) NOT NULL,
  PHONE varchar(50) NOT NULL,
  AVAILABLE_BALANCE decimal(10,2) NOT NULL,
  MEMBERSHIP_START_DATE date NOT NULL,
  MEMBERSHIP_END_DATE date NOT NULL,
  CARD_STATUS tinyint(1) NOT NULL,
  PRIMARY KEY (`PASSENGER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO TRANSPORT_MANAGEMENT.DESTINATION_CHARGES
VALUES('Zone1','Zone2',40.00);
INSERT INTO TRANSPORT_MANAGEMENT.DESTINATION_CHARGES
VALUES('Zone2','Zone1',40.00);
INSERT INTO TRANSPORT_MANAGEMENT.DESTINATION_CHARGES
VALUES('Zone1','Zone3',65.00);
INSERT INTO TRANSPORT_MANAGEMENT.DESTINATION_CHARGES
VALUES('Zone3','Zone1',65.00);
INSERT INTO TRANSPORT_MANAGEMENT.DESTINATION_CHARGES
VALUES('Zone1','Zone4',85.00);
INSERT INTO TRANSPORT_MANAGEMENT.DESTINATION_CHARGES
VALUES('Zone4','Zone1',85.00);
INSERT INTO TRANSPORT_MANAGEMENT.DESTINATION_CHARGES
VALUES('Zone2','Zone3',40.00);
INSERT INTO TRANSPORT_MANAGEMENT.DESTINATION_CHARGES
VALUES('Zone3','Zone2',40.00);
INSERT INTO TRANSPORT_MANAGEMENT.DESTINATION_CHARGES
VALUES('Zone2','Zone4',70.00);
INSERT INTO TRANSPORT_MANAGEMENT.DESTINATION_CHARGES
VALUES('Zone4','Zone2',70.00);
INSERT INTO TRANSPORT_MANAGEMENT.DESTINATION_CHARGES
VALUES('Zone3','Zone4',40.00);
INSERT INTO TRANSPORT_MANAGEMENT.DESTINATION_CHARGES
VALUES('Zone4','Zone3',40.00);